### ISSUE TITLE
Wasn't it supposed to be written in c using the graphics.h library?

### ISSUE THREAD

**Issue by werainkhatri** [priyanshisharma/Traffic-Light-Animation#1]

**Comment by priyanshisharma** [comment]
It said C/ C++/ OpenGL/ **Python**.

PS - I've sent this in this repository in the CG Lab Classroom, if he gives an update, I'll let you know.

![IMG_8147](https://user-images.githubusercontent.com/30956619/101393217-bd0b3e00-38ec-11eb-8447-b86ac4775799.jpg)

**Comment by werainkhatri** [comment]
Oh okay cool. Thanks for the update!
